defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"


include: ["_static"]
exclude: ["sphinx", "README.md", "Gemfile*", ".gitignore"]
markdown: rdiscount
permalink: pretty
baseurl: /sci-wms
